package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.65

import (
	"context"
	"fmt"
	"graphql-demo/graph/model"
)

// CreateServer is the resolver for the createServer field.
func (r *mutationResolver) CreateServer(ctx context.Context, input model.CreateServerInput) (*model.ServerMutationPayload, error) {
	panic(fmt.Errorf("not implemented: CreateServer - createServer"))
}

// Servers is the resolver for the servers field.
func (r *queryResolver) Servers(ctx context.Context, filter *model.ServerFilter, pagination *model.PaginationInput) ([]*model.ServerList, error) {
	panic(fmt.Errorf("not implemented: Servers - servers"))
}

// Server is the resolver for the server field.
func (r *queryResolver) Server(ctx context.Context, id string) (*model.Server, error) {
	panic(fmt.Errorf("not implemented: Server - server"))
}
